components:
- name: DocumentStore
  params:
    embedding_dim: 768
    embedding_field: emb
    excluded_meta_data:
    - emb
    index: tutorial5_docs
    label_index: tutorial5_labels
  type: ElasticsearchDocumentStore

- name: Preprocessor
  params:
    clean_empty_lines: false
    clean_whitespace: false
    split_length: 400
    split_overlap: 0
    split_respect_sentence_boundary: false
    split_by: word
  type: PreProcessor

- name: Retriever_elastic
  params:
    document_store: DocumentStore
  type: BM25Retriever
- name: JoinResults
  params: {}
  type: JoinDocuments

- name: Retriever
  params:
    document_store: DocumentStore
    embed_title: false
    max_seq_len_query: 64
    max_seq_len_passage: 400
    passage_embedding_model: /opt/models/retriever_finalTrain_overfitt/passage_encoder
    query_embedding_model: /opt/models/retriever_finalTrain_overfitt/query_encoder
  type: DensePassageRetriever
- name: Reader
  params:
    model_name_or_path: /opt/models/reader_mydataset3
  type: FARMReader

#- name: TextConverter
#  params: {}
#  type: TextConverter

- name: TextFileConverter
  type: TextConverter
- name: PDFFileConverter
  type: PDFToTextConverter
- name: FileTypeClassifier
  type: FileTypeClassifier



pipelines:
- name: query
  nodes:
  - inputs:
    - Query
    name: Retriever
  - inputs:
    - Query
    name: Retriever_elastic
  - inputs:
    - Retriever_elastic
    - Retriever
    name: JoinResults
  - inputs:
    - JoinResults
    name: Reader


- name: indexing
  nodes:
    - name: FileTypeClassifier
      inputs: [File]
    - name: TextFileConverter
      inputs: [FileTypeClassifier.output_1]
    - name: PDFFileConverter
      inputs: [FileTypeClassifier.output_2]
    - name: Preprocessor
      inputs: [PDFFileConverter, TextFileConverter]
    - name: Retriever
      inputs: [Preprocessor]
    - name: DocumentStore
      inputs: [Retriever]
#- name: indexing
#  nodes:
#  - inputs:
#    - File
#    name: TextConverter
#  - inputs:
#    - TextConverter
#    name: Preprocessor
#  - inputs:
#    - Preprocessor.output_1
#    name: Retriever_elastic
#  - inputs:
#    - Preprocessor.output_1
#    name: Retriever
#  - inputs:
#    - Retriever_elastic
#    - Retriever
#    name: JoinResults
#  - inputs:
#    - JoinResults
#    name: DocumentStore
version: 1.22.1
